### ISSUE TITLE
[feat] Move `Language`, `Theme` & `Debug` into `Config` or `Settings`

### ISSUE THREAD

**Issue by moritz-t-w** [szczyglis-dev/py-gpt#10]
I think `Language`, `Theme` and `Debug` don't belong in the top bar.
It would look less overwhelming if they were all inside of the `Config` submenu
![mockup with language & debug](https://github.com/szczyglis-dev/py-gpt/assets/90388353/3c328b6f-b095-41c2-bae1-730b4403d383)
In fact, changing the language is such an infrequent use case that I think it belongs in the `Settings`:
![mockup with debug](https://github.com/szczyglis-dev/py-gpt/assets/90388353/c6b0e95a-6302-44bc-b1c9-fc902b9f71be)
The `Debug` config is also not something the average user will use, so I think it could also be in `Settings`.
![mockup without either](https://github.com/szczyglis-dev/py-gpt/assets/90388353/545a666a-9628-4df9-90c9-49645b77e837)

**Comment by moritz-t-w** [comment]
If you agree, I will implement whichever solution turns out to fit best :)

**Comment by szczyglis-dev** [comment]
Sure, I agree, you can go ahead :)
I also think that the clearest option will be the last one, which is moving Theme to Config, and Language and Debug to Settings.

**Comment by moritz-t-w** [comment]
Ok I will get to work on this. Could you just assign it to me so I can keep track of it?

**Comment by moritz-t-w** [comment]
So.. tbh I thought this would be a lot less complicated lol. I don't think I have the capacity atm to dive into the code, sorry. :<

**Comment by szczyglis-dev** [comment]
Oops, I didn't assign you to this task, sorry about that (too many things to juggle at once and I missed it).
No worries, it's OK. If that's the case, I'll just handle it on my own in one of the upcoming updates ;)

**Comment by szczyglis-dev** [comment]
Added in release [2.0.116](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.0.116) ;)
