### ISSUE TITLE
[feat] Screenshot

### ISSUE THREAD

**Issue by moritz-t-w** [szczyglis-dev/py-gpt#11]
The status icon could have a button in the dropdown to ask chatgpt about what's on screen
![mockup](https://github.com/szczyglis-dev/py-gpt/assets/90388353/c554c3f4-1bed-469f-a100-e59401f9ed94)

**Comment by szczyglis-dev** [comment]
That feature sounds really great! :)
It will be implemented in one of the upcoming versions.

**Comment by moritztim** [comment]
@bukit-kronik:
> how can I bind hotkey to the "Ask with screenshot" command?

I may be wrong but I don't think you can. Maybe open a new issue about that
