### ISSUE TITLE
[feat] Let status indicator indicate status

### ISSUE THREAD

**Issue by moritz-t-w** [szczyglis-dev/py-gpt#12]
The status indicator in the top bar could indicate that the ai is typing by having 3 dots in the logo and maybe a `1` when there's a new unread response since the app has lost focus. Nothing in the speech bubble would be an idle state and a `!` could indicate when there was an API error.

**Comment by szczyglis-dev** [comment]
Status indicator in tray icon added in release: [2.0.130](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.0.130)
