### ISSUE TITLE
[feat] Make `New Context...` open the app

### ISSUE THREAD

**Issue by moritz-t-w** [szczyglis-dev/py-gpt#13]
Currently, when clicking on `New Context...` in the top bar status symbol, a new context is created but the app does not gain focus
![New Context... button](https://github.com/szczyglis-dev/py-gpt/assets/90388353/fd3b8acb-c766-4073-98b6-0268ea49fa84)
I think it would make sense to also bring the app into focus when the button is clicked

**Comment by szczyglis-dev** [comment]
Added in release: [2.0.109](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.0.109)
