### ISSUE TITLE
Is a status icon really needed?

### ISSUE THREAD

**Issue by moritz-t-w** [szczyglis-dev/py-gpt#15]
![current options](https://github.com/szczyglis-dev/py-gpt/assets/90388353/8b1d9cbb-5102-40e5-af2a-7077628e6d3e)
I don't think checking for updates or opening the github repo are options that need to be quickly available from the status icon. I think a status icon is only warranted if it offers some value that the application can't offer from its own top bar.
There should at least be the option to disable the icon.

Don't get me wrong, I think the icon could be useful, I even have some suggestions for useful features:
- #11
- #12
- #13
- #14

But in my opinion, until more useful features, such as these ideas, are implemented, it just doesn't seem justified to take up a part of my top bar space, which will take away space from actually useful UI elements in the top bar.

**Comment by moritz-t-w** [comment]
https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#Menu-bar-extras
> Let people — not your app — decide whether to put your menu bar extra in the menu bar.

https://developer.apple.com/documentation/swiftui/menubarextra
> Use a MenuBarExtra when you want to provide access to **commonly used functionality**, even when your app is not active.

**Comment by szczyglis-dev** [comment]
Yes, I agree. There aren't too many useful options in the taskbar right now.
But I'm in favor of keeping it and adding more functionality to it.
Screenshot and notepad sound great! They will be implemented in one of the upcoming releases.
There are also plans to control scheduled tasks from the Task Scheduler plugin from the status icon.

**Comment by moritz-t-w** [comment]
That sounds great! I'm also in favor of adding use to it and keeping it, but do make sure to allow it to be disabled in the settings, as to not impose

**Comment by szczyglis-dev** [comment]
Ok, features was added, tray icon stay in position, so I'm closing ;)
