### ISSUE TITLE
Installation problem on linux

### ISSUE THREAD

**Issue by ztxjack** [szczyglis-dev/py-gpt#18]
I have downloaded latest source code from github and try on ubuntu18 OS --- either python3.10 or 3.9
but all failed with same prompt message:
```
ERROR: Could not find a version that satisfies the requirement PySide6==6.4.2 (from versions: 6.0.0a1.dev1606911628, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.2.0, 6.2.1, 6.2.2, 6.2.2.1, 6.2.3, 6.2.4)
ERROR: No matching distribution found for PySide6==6.4.2
```
and I have no idea how it can be working or i can use other version that could be working on my environment.
so can someone help me on this, thanks.

**Comment by szczyglis-dev** [comment]
Did you try in virtual env?

**Comment by ztxjack** [comment]
Hi @szczyglis-dev ,
I have tried it either in venv or conda env but still got error messages:

```
ERROR: Ignored the following versions that require a different python version: 6.0.0 Requires-Python >=3.6, <3.10; 6.0.0a1.dev1606911628 Requires-Python >=3.6, <3.10; 6.0.1 Requires-Python >=3.6, <3.10; 6.0.2 Requires-Python >=3.6, <3.10; 6.0.3 Requires-Python >=3.6, <3.10; 6.0.4 Requires-Python >=3.6, <3.10; 6.1.0 Requires-Python >=3.6, <3.10; 6.1.1 Requires-Python >=3.6, <3.10; 6.1.2 Requires-Python >=3.6, <3.10; 6.1.3 Requires-Python >=3.6, <3.10
ERROR: Could not find a version that satisfies the requirement PySide6==6.4.2 (from versions: 6.2.0, 6.2.1, 6.2.2, 6.2.2.1, 6.2.3, 6.2.4)
ERROR: No matching distribution found for PySide6==6.4.2
```
So do you have any idea on this?

**Comment by szczyglis-dev** [comment]
Maybe try to install PySide6 manually by downloading it from PyPi and installing it with:

```
pip install --ignore-installed <package-file.whl>
```

You can download PySide6 from here: https://pypi.org/project/PySide6/#files

**Comment by ztxjack** [comment]
@szczyglis-dev ,
Thanks for your suggestion, while unfortunately it is still not working on 
either python3.10 or 3.11 environment on Ubuntu
which I got following message when trying to install the 6.4.2 version by the way of a wheel package 

`ERROR: PySide6-6.4.2-cp37-abi3-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.`

So I'm not sure which version are you using now or find a matching one on linux, thanks.

**Comment by szczyglis-dev** [comment]
`6.4.2` is used by the app, but versions greater than `6.4.2` should also work.
