### ISSUE TITLE
new "input" line with "enter" option enabled can't be created

### ISSUE THREAD

**Issue by oleksii-honchar** [szczyglis-dev/py-gpt#26]
I'm not able to create new "input" line with "Enter" option enabled. Any combination which includes "Enter" (e.g. Alt+Enter, Shift+Enter) as a part of it submits "input".

I'm able to create new line in "input" with "Shift+Enter" option enabled using "Enter". And then send it using "shift+enter" combination.
<img src="https://github.com/szczyglis-dev/py-gpt/assets/8767148/e6110b3f-ee30-4d4e-95d3-f56fe1983f42" width="600">

Is this a bug or feature?

**Comment by szczyglis-dev** [comment]
No, this is not a bug, that's how it's supposed to work.

New lines can be added with "Enter" key only when sending with "Shift+Enter" is enabled.
