### ISSUE TITLE
no word-wrap  in code blocks

### ISSUE THREAD

**Issue by oleksii-honchar** [szczyglis-dev/py-gpt#27]
version: 2.1.14

There is no word-wrap for code block content
<image src="https://github.com/szczyglis-dev/py-gpt/assets/8767148/0babbe3f-df05-4efd-a355-60ce78ba5b7e" width="600"/>

I can't find in docs if it possible to enable it.

**Comment by szczyglis-dev** [comment]
Fixed in `2.1.16`. Thanks!
