### ISSUE TITLE
typo in gpt4 model id

### ISSUE THREAD

**Issue by oleksii-honchar** [szczyglis-dev/py-gpt#29]
Chat with files work fine using gpt3-16k, but when switched to gpt-4-turbo-preview it throws the error.
![image](https://github.com/szczyglis-dev/py-gpt/assets/8767148/08839caa-b7c3-4c12-84a5-cd4b4a37fa31)

**Comment by szczyglis-dev** [comment]
Fixed in: `2.1.15`. Thanks!
