### ISSUE TITLE
No settings option in plugins. (PyGPT v0.9.6 | build 2023.04.16)

### ISSUE THREAD

**Issue by soccerwithag** [szczyglis-dev/py-gpt#3]
As title states, there is no place to configure the settings for plugins (such as api keys). 

Running on MacOS, installed in venv from source.

Otherwise working fine.

<img width="516" alt="image" src="https://github.com/szczyglis-dev/py-gpt/assets/93694026/33398f17-ee4e-41b3-895e-43febd72fe0a">

**Comment by szczyglis-dev** [comment]
Is this issue still exists in newest version?
