### ISSUE TITLE
plugin options left sidebar size is not responsive 

### ISSUE THREAD

**Issue by oleksii-honchar** [szczyglis-dev/py-gpt#30]
**OS**: MacOs Sonoma 14.4
Started from source using `shortcut.sh`

# Actual behavior

"Plugins" settings screen shows left sidebar very small. Options window resize has no effect
<img src="https://github.com/szczyglis-dev/py-gpt/assets/8767148/c158896d-c7de-4783-ac1a-ca3b2d46f503" width="600">

# Expected behavior

"Plugins" settings screen shows left sidebar respect to window size, same as for "Config:Settings" window
<img src="https://github.com/szczyglis-dev/py-gpt/assets/8767148/0878c837-f5e6-4b90-917f-8838d5da4167" width="600">

**Comment by szczyglis-dev** [comment]
In version `2.1.18`, horizontal splitters in dialogs have been added + min. width for the lists has been set - it should be OK now on MacOS.

**Comment by oleksii-honchar** [comment]
Yes, now it's good. Thanks!
