### ISSUE TITLE
question: how to fix indexed file types?

### ISSUE THREAD

**Issue by oleksii-honchar** [szczyglis-dev/py-gpt#32]
pygpt version: 2.1.18

I noticed that in the "FILES" tab and chat, when the LlamaIndex source is referenced, it provides the wrong file type, for example, "file_type: video/mp2t."

From what I've read on internet about RAG this can affect q&a quality, when for document used wrong meta information. Is it possible to fix types for source code files?

<img width="600" alt="image" src="https://github.com/szczyglis-dev/py-gpt/assets/8767148/073dd981-af8a-4b77-878b-956252878cba">

**Comment by szczyglis-dev** [comment]
From version `2.1.19`, there is a new option: `Settings -> Llama-index -> Custom metadata`.

In this option you can define custom fields in document metadata, which will be included during file indexing and overwrite those generated by Llama index data loaders. Just create a new entry for extension `ts` with key `file_type` and value `your_custom_file_type_here` and re-index the files.
