### ISSUE TITLE
question: how to use different embedding model, e.g. text-embedding-3-small?

### ISSUE THREAD

**Issue by oleksii-honchar** [szczyglis-dev/py-gpt#34]
<img src="https://github.com/szczyglis-dev/py-gpt/assets/8767148/9d2119d9-d310-4b95-915b-d4998affd215" width="600">

**Comment by szczyglis-dev** [comment]
There is no option for this at the moment. Maybe it will be added in the future.

**Comment by szczyglis-dev** [comment]
Configuration for embedding model was added in `2.1.23`: `Settings -> Indexes (Llama-index) -> Embeddings`.
