### ISSUE TITLE
Monospace font

### ISSUE THREAD

**Issue by linnflux** [szczyglis-dev/py-gpt#37]
Brilliant program! 

Certain use cases require monospace font output. Editing CSS does not yield results for this. 

Using snap version. Thank you!

**Comment by szczyglis-dev** [comment]
Thanks!

The `Space Mono` font has been added in `2.1.33`.

To update font in already defined custom CSS:

```
// markdown.*.css

pre {{
    font-family: 'Space Mono';
}}
code {{
    font-family: 'Space Mono';
}}
```

**Comment by linnflux** [comment]
Thank you! Works perfectly.
