### ISSUE TITLE
feature request - code formatting

### ISSUE THREAD

**Issue by glinkot** [szczyglis-dev/py-gpt#43]
Would be nice to have two features on code (see screenshot from heyGPT, which has been abandoned but has been my go-to until I found pyGPT):

- Code highlighting
- The convenience feature where the code appears in a code box, with a 'copy' button at the top.

![image](https://github.com/szczyglis-dev/py-gpt/assets/13640691/ed8a7046-e3cf-4212-b793-646274c8f91c)

**Comment by glinkot** [comment]
I notice this project which could help with the syntax highlighting:

https://pygments.org/

**Comment by szczyglis-dev** [comment]
Copy to clipboard button added in [2.1.45](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.1.45). Thanks!

Code highlighting coming soon.

**Comment by glinkot** [comment]
Another notable thing - the one I use applies the code highlighting in real time as the text comes through, rather than just once at the end.  That's really useful as you watch it spool out.

**Comment by glinkot** [comment]
I downloaded 2.1.46 that mentioned improved code formatting, but I didn't notice differences yet.  Thanks so much for looking into it though!

**Comment by szczyglis-dev** [comment]
Syntax highlighting added in **2.1.59**:


# 2.1.59 (2024-04-20)

- Added output renderer: WebEngine/Chromium – with full HTML/CSS/JS support. (Experimental)
- Added a new option to choose a render engine in Settings -> General -> Rendering engine to select between WebEngine / Chromium mode and the Legacy mode (old, with simple markdown CSS support only - for compatibility reasons and troubleshooting).
- Added syntax highlighting to code blocks – issue #43.
- Added a new option in Settings -> Layout -> Code syntax highlight to select a highlight theme.
- Added a new option in Settings -> Context -> Convert lists to paragraphs to enable/disable converting ul and li into p for better copying.
- Copy to clipboard and regenerate response icons are now visible by default.

**Comment by glinkot** [comment]
This is awesome!  Do you think it runs quickly enough that we could apply the highlight after each word or few words as it streams out of the API, rather than once at the end?

**Comment by glinkot** [comment]
Also it would be good to put any unrecognised syntaxes into a monospaced code box rather than leaving the backticks (example of each shown)

![image](https://github.com/szczyglis-dev/py-gpt/assets/13640691/3a8423c1-90fa-4071-a1a7-20fbe17a0168)

![image](https://github.com/szczyglis-dev/py-gpt/assets/13640691/ef892fbc-9590-47ff-9a6a-1fa359c7a5aa)

**Comment by szczyglis-dev** [comment]
> This is awesome! Do you think it runs quickly enough that we could apply the highlight after each word or few words as it streams out of the API, rather than once at the end?

Thanks ;) And yes, real-time formatting in stream mode has just been added in version 2.1.61 (it also works for syntax highlighting).

### 2.1.61 (2024-04-21)

- Added real-time HTML formatting of text chunks in stream mode.
