### ISSUE TITLE
feature request - paste image

### ISSUE THREAD

**Issue by glinkot** [szczyglis-dev/py-gpt#44]
For speed of workflow, I'd love it if I could ctrl-V when entering my input, to add the current clipboard image (or other media type I guess) as an attachment to my GPT Vision prompt or similar.

The workflow of taking a screenshot, saving it to a folder, then browsing to it from pyGPT adds some friction when doing stuff like "here is my interface, what should I click on' type things.

**Comment by szczyglis-dev** [comment]
Pasting images as attachments in input using ctrl-V added in [2.1.45](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.1.45). Thanks!

By the way, you can take screenshots using the 'Ask with screenshot' option from the tray icon - an attachment is created automatically.

**Comment by glinkot** [comment]
Fantastic!  Thanks so much mate!
