### ISSUE TITLE
feature request - ctrl-enter to send

### ISSUE THREAD

**Issue by glinkot** [szczyglis-dev/py-gpt#45]
I see shift-enter is offered for sending the chat, which is so much better than having enter do it.  However the standard hotkey for this (in slack, gmail and many others) is ctrl-enter.  Could we have that as an option please?

**Comment by szczyglis-dev** [comment]
Added in [2.1.47](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.1.47):

Ctrl+Enter and Shift+Enter now both work in "Shift+Enter" mode.

**Comment by glinkot** [comment]
Amazing!  Thanks for this!

**Comment by glinkot** [comment]
One small point here - in many programs 'shift plus enter' is actually 'do a new line when enter is commit'.  So, you hold shift-enter for newline.  Having both controlled by one flag does mean some accidental submitting might happen.  Was a great step forward though :)
