### ISSUE TITLE
feature request - box per prompt or response, with delete/edit options

### ISSUE THREAD

**Issue by glinkot** [szczyglis-dev/py-gpt#46]
In the 'chat' window, the prompt (grey in my example) and response (white) run together in one window.

I see an 'edit' checkbox below the chat window, that lets me remove one part of the conversation, but it isn't super obvious which bit will be deleted.  Better would be a box per prompt or response, each with such buttons, so you know what it is you're removing.  

Would be super helpful!  Also very useful to understand what came from yourself vs it.

![image](https://github.com/szczyglis-dev/py-gpt/assets/13640691/ef82a211-ad6f-4f23-8884-91836d161a2d)

**Comment by szczyglis-dev** [comment]
Chat messages from release **2.1.76** are now displayed in blocks. ;)

![messages](https://github.com/szczyglis-dev/py-gpt/assets/61396542/10f547f7-66d3-4410-a5bb-24edb92a6b46)

(Block display can be turned off via Menu -> Theme -> Display blocks)

**Comment by glinkot** [comment]
Fantastic!!
