### ISSUE TITLE
Understanding context groups

### ISSUE THREAD

**Issue by glinkot** [szczyglis-dev/py-gpt#47]
Just loving this tool!  So awesome, so apologies if I've been sending a few requests your way.

I was seeing if there were 'tabs' or something to categorise subjects.  It seems the concept is there, as 'context groups'.  It seems I can create one, then move existing chats into that group.  What I can't see is how to say "right now, the active subject (ie context group) I'm doing is unity game dev.  All new conversations I start should be in there, until I choose a different one (eg health) later on."

I tried highlighting a context group before starting a new conversation, but the convo still appears at the top of the history box. 

Suggestion:
- If a certain context group (or child of a certain context group) is active, new conversations are created under it also
- Or, probably a bit more work, a box similar to the 'mode' or 'model' box appears, with a list of your subject areas, and you select the one that any newly created chats will go to.

Thanks for listening!

**Comment by szczyglis-dev** [comment]
Thank you! This one was added in [2.1.47](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.1.47):

From now - if the group is active or the current context is in the group, then a new context created via "New..." button is created under this group.

**Comment by glinkot** [comment]
Yes, this is great and acts exactly as I pictured it.  You are a guru!
