### ISSUE TITLE
Feature request - Markdown rendering

### ISSUE THREAD

**Issue by glinkot** [szczyglis-dev/py-gpt#49]
Per screenshots, would be great to render markdown (realtime as it streams ideally).  Comparison:

![image](https://github.com/szczyglis-dev/py-gpt/assets/13640691/02063e48-5d39-4886-989e-96aa15f6cc33)

![image](https://github.com/szczyglis-dev/py-gpt/assets/13640691/277217e3-24e8-474a-a42a-f28a5019a0ed)

**Comment by szczyglis-dev** [comment]
Closing because markdown is currently rendered in web view.
