### ISSUE TITLE
Using PyGPT with local PrivateGPT

### ISSUE THREAD

**Issue by AnonTester** [szczyglis-dev/py-gpt#52]
I'm trying to use my own OpenAI API compatible privateGPT model with PyGPT v2.2.4, but when pointing the API endpoint to my internal remote server, I get popup prompts about missing OpenAI API Keys.

Please allow the use of custom OpenAI API compatible endpoints without an OpenAI API key or Org key for local use.

The model selection could do with gpt-custom option.

Background: I do not want to send any of my data to the OpenAI endpoints, but use own local models instead. The local model is on a remote system as my local system does not have a discrete GPU.

If I'm missing anything obvious, please advise.

**Comment by szczyglis-dev** [comment]
You can just enter anything into the API key field, like "xxxx", it will turn off the prompt asking for the key. Does this not solve the problem?

**Comment by szczyglis-dev** [comment]
Just disable the plugins you don't want to use—plugins, like DALL-E 3 (inline) and others add their own instructions to the system prompt. GPT-3.5 is not very smart at interpreting these instructions. ;)

**Comment by szczyglis-dev** [comment]
Only one system prompt is sent. Additional parts are added by plugins (and by activating a plugin, you declare that you are using it). Plugins are designed more for GPT-4; GPT-3.5 does not handle many things well.

**Comment by szczyglis-dev** [comment]
Yes, that's correct. OK, for now, I've just turned off by default plugins that add their own instructions to the prompts (essentially, it was only DALL-E). Anyone who wants to use plugins will be able to experiment with them on their own, but at the start, it won't create confusion. Thanks for your suggestion!
