### ISSUE TITLE
agent installing libraries for code interpreter 

### ISSUE THREAD

**Issue by flugenheimer** [szczyglis-dev/py-gpt#54]
Hello, 

Is there a way for the Agent to install relevant libraries automatically. 

As a test i wanted the agent to train a classification network to classify the MNIST dataset and tell me the resulting accuracy. 
The agent creates the network using Tensorflow, but can not execute in the code interpreter because tensorflow is not installed using pip. 

I have tried multi agent systems like Autogen where one of the agents then install the missing library and is able to continue. Is this also feasable here? 

Kind Regards

**Comment by szczyglis-dev** [comment]
Coming soon: https://github.com/szczyglis-dev/py-gpt/issues/67#issuecomment-2475504676

**Comment by szczyglis-dev** [comment]
Code Interpreter (v2) with IPython is available from version: [2.4.13](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.4.13)

From now, it is possible to install new libraries and use the Code Interpreter just like Jupyter. It works in Docker, so it requires Docker to be installed (the Snap version has it built-in).
