### ISSUE TITLE
this app vs. GPT browser version

### ISSUE THREAD

**Issue by tpl** [szczyglis-dev/py-gpt#56]
What can this application actually do more than the browser-based version of GPT. 
Where there is an advantage ?

**Comment by Pointfit** [comment]
I am thinking the same thing

**Comment by gfsysa** [comment]
ah, check the read.me

**Comment by gfsysa** [comment]
Even easier:

> Supports multiple models: GPT-4, GPT-4 Vision, GPT-3.5 and any Langchain LLMs.
> 9 modes of operation: chat, assistant, completion, image generation, autonomous agents, experts, vision analysis, Langchain and Chat with files (Llama-index).
> Included support features for individuals with disabilities: customizable keyboard shortcuts, voice control, and translation of on-screen actions into audio via speech synthesis.
> Speech synthesis using Microsoft Azure, OpenAI TTS, Google and Eleven Labs.
> Speech recognition using OpenAI Whisper, Google and Microsoft Bing.
> Real-time internet access via Google and Microsoft Bing.
> Execution of Python code and system commands.
> Integration with OS and external services via API calls.
> Access to the OS filesystem.
> Vector embeddings and chat with files via Llama-index.
> Image generation using DALL-E 3.
> Image analysis using GPT-4 Vision.
> Short and long-term memory capabilities.
> Storage and restoration of context and conversation history.
> Editable prompt presets.
> Ability to support future OpenAI models, like GPT-5.
> Extendable with plugins.
> Built-in token usage calculation.
> Open source: full source code available on GitHub.
