### ISSUE TITLE
Trying to index files continues even after a rate limit error

### ISSUE THREAD

**Issue by helsingi** [szczyglis-dev/py-gpt#66]
App version 2.2.19 running on Windows 11

**Issue:**
After uploading files and pressing "INDEX ALL" the code attempts to index each and every file regardless of the error received from openai about the quota exceeded. Then of course the error keeps appearing for all the files and I need to wait for the process (attempting to index each file) to finish to see which files were successfully indexed before the rate limit being hit. After the wait, a pop-up window appears with all the errors regarding each file.

**Error Message:**
`Error while indexing file: filepath.pdf
Type: RateLimitErrorMessage: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}`

**Suggestion:**
To stop the process of trying to index files once an error occurs that data limit has been reached or quota exceeded.

Thanks for the great app!

**Comment by szczyglis-dev** [comment]
In version `2.2.22`:

- Added a new option in Config -> Indexes (llama-index) -> Indexing -> **Stop indexing on error.** 
If enabled, indexing will stop whenever an error occurs. Default: True
