### ISSUE TITLE
Question: how can i get an agent to install a library when it is missing? 

### ISSUE THREAD

**Issue by loke-bager** [szczyglis-dev/py-gpt#67]
Is there a way to get an agent to install a library when it is not part of the docker container? 

i have tried Autogen, and it worked really for with one agent writing code, another running it, one looking at error messages and suggesting fixed, then loop. 

not sure how to achieve something similar here? 

for testing purposes i want to train a machine learning image classifier for the MNIST dataset.

**Comment by szczyglis-dev** [comment]
Extended `Code Interpreter` plugin working in connection with `Jupyter Notebook` in Docker will be available soon. It will be possible to install missing libraries "on-the-fly" :)

**Comment by szczyglis-dev** [comment]
Code Interpreter (v2) with IPython is available from version:  [2.4.13](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.4.13
)

From now, it is possible to install new libraries and use the Code Interpreter just like Jupyter. It works in Docker, so it requires Docker to be installed (the Snap version has it built-in).
