### ISSUE TITLE
[feat] Plugin description tooltip

### ISSUE THREAD

**Issue by moritz-t-w** [szczyglis-dev/py-gpt#7]
Instead of having to click on `Plugins`>`Settings`>`<plugin name>` it would be nice to get a short description of each plugin by hovering over `Plugins`>`<plugin name>`

**Comment by szczyglis-dev** [comment]
Yes, this is very good idea. I agree with that. :)

**Comment by szczyglis-dev** [comment]
Added in release: [2.0.109](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.0.109)
