### ISSUE TITLE
version 2.4.9 fail after upgrade

### ISSUE THREAD

**Issue by proitservices** [szczyglis-dev/py-gpt#73]
Hi, 

Just updated via snap to 2.4.9
commands:
  - pygpt
snap-id:      c0Brljab75R0J5x0Gq5IdzPcD69IPzCF
tracking:     latest/stable
refresh-date: today at 15:12 GMT
channels:
  latest/stable:    2.4.9 2024-11-12 (276) 969MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      ↑                            
installed:          2.4.9            (276) 969MB -

The application worked few minutes ago on 2.4.8 but this version is no longer available.

OS release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"

packages
apt show python3-dev
Package: python3-dev
Version: 3.12.3-0ubuntu2

apt show python3-tk
Package: python3-tk
Version: 3.12.3-0ubuntu1

python3-tk is already the newest version (3.12.3-0ubuntu1).
python3-dev is already the newest version (3.12.3-0ubuntu2).

Issues I see from logs:
journalctl

Nov 12 15:40:32 piotr-HP-ProBook-430-G7 systemd[1991]: Started snap.pygpt.pygpt-b56ed575-502d-419a-8de7-d7fa1e2c73c0.scope.
Nov 12 15:40:32 piotr-HP-ProBook-430-G7 kernel: audit: type=1400 audit(1731426032.369:849): apparmor="DENIED" operation="open" class="file" profile="snap-update-ns.pygpt" name="/proc/15043/maps" pid=15043 comm="5" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 12 15:40:32 piotr-HP-ProBook-430-G7 kernel: audit: type=1400 audit(1731426032.689:850): apparmor="DENIED" operation="open" class="file" profile="snap.pygpt.pygpt" name="/snap/core22/1663/usr/lib/x86_64-linux-gnu/libpcre.so.3.13.3" pid=15091 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 12 15:40:35 piotr-HP-ProBook-430-G7 pygpt_pygpt.desktop[15091]: NOTE: You must install tkinter on Linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev
Nov 12 15:40:35 piotr-HP-ProBook-430-G7 systemd[1991]: snap.pygpt.pygpt-b56ed575-502d-419a-8de7-d7fa1e2c73c0.scope: Consumed 4.041s CPU time.

Can you please advise?

**Comment by szczyglis-dev** [comment]
Hi, this is already fixed in: `2.4.10`

**Comment by proitservices** [comment]
Great, thank you for the quick turn around. Weill keep you posted.
