### ISSUE TITLE
Won't launch after update. Ubuntu 24.04.

### ISSUE THREAD

**Issue by Hade231** [szczyglis-dev/py-gpt#74]
I tried these commands:
sudo snap remove pygpt
sudo snap install pygpt

Same thing. After the update to 2.4.9 the app won't start. 

Please investigate .
Thank you.

**Comment by szczyglis-dev** [comment]
Hi, this is already fixed in: 2.4.10

**Comment by Hade231** [comment]
Issue is back after the latest update. App can't be launch.
