### ISSUE TITLE
Freeze when want to install update

### ISSUE THREAD

**Issue by massam89** [szczyglis-dev/py-gpt#75]
![Capture](https://github.com/user-attachments/assets/96c042da-acdf-4e9b-9da8-98b2ac5cf806)

**Comment by mohammadhoseinazaddel** [comment]
comment that " I agree to the...." cant chose for near 5 minutes

**Comment by mohammadhoseinazaddel** [comment]
Comment that " I agree to the...." can't chose for nearly 5 minutes

**Comment by szczyglis-dev** [comment]
Yes, I know, it's an issue in Advanced Installer... I fixed it in version:


[2.4.20](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.4.20)


It should no longer "freeze" during installation.
