### ISSUE TITLE
Error reading Attachments: 'NoneType' object has no attribute 'append'

### ISSUE THREAD

**Issue by purpleturtle1988** [szczyglis-dev/py-gpt#78]
Dear Developer,

I've encountered a problem that occurs when I try to upload a file, such as a PDF, for analysis. Each time, I receive the following error message: "Error reading Attachments: 'NoneType' object has no attribute 'append'".

I would greatly appreciate your assistance in resolving this issue.

Thank you in advance for your support.

Best regards

**Comment by szczyglis-dev** [comment]
Fixed in: [2.4.28](https://github.com/szczyglis-dev/py-gpt/releases/tag/v2.4.28)
