### ISSUE TITLE
How to move the config files to sub directory "mysettings" of PyGPT installation directory?

### ISSUE THREAD

**Issue by pstein** [szczyglis-dev/py-gpt#81]
As far as I can see PyGPT stores all settings in 

C:\Users\<username>\\.config\pygpt-net\

How can I tell PyGPT to move these files to a subdirectory (e.g. "myettings") of the PyGPT installation directory e.g.

D:\tools\GPT\pygpt\mysettings\

?

**Comment by szczyglis-dev** [comment]
You can change the profile by navigating to menu `Config` -> `Profile` -> `New profile` or `Edit profiles` <- and provide a new path to the profile on disk, or by going to menu `Config` -> `Change working directory`.

**Comment by pstein** [comment]
This is NOT working.

I changed as suggested menu Config -> Change working directory.
At first it seems tot work.

Then I deleted directory
C:\Users<username\.config\pygpt-net\

When I restarted now PyGPT all previous settings are lost.
So PyGPT is not completely portable. I cannot run it from USB flash drive.

Maybe there is a way to pass the new working directory on cmdline?
Something like:

pygpt.exe --workingdir="D:\tools\GPT\pygpt\mysettings\"

**Comment by szczyglis-dev** [comment]
It works, but not in the way you describe.


After changing the working directory to any other one, a file named `path.cfg` is saved in the user's directory at `C:\Users\<username\.config\pygpt-net\` with the path pointing to the directory where the last loaded profile directs or where it was moved. By deleting this directory, you removed the information about the path indicating where the moved directory is located.


Anyway, I added a new command-line argument `--workdir` in version `2.4.36`.


Running with the argument `--workdir=/path/to` now directly points to the given directory, bypassing the check for the moved directory path in the user directory.

**Comment by pstein** [comment]
Thank you, but there is still a bug.

If I start pypgt with

pygpt.exe --wordir="D:\tools\GPT\pygpt\mysettings"

then the previously deleted folder C:\Users\<username>\.config\pygpt-net\ is re-created again with and EMPTY path.cfg and app.log files inside. What is needed is a complete portable installation which does not leave traces.

Why not simple let pygpt check in its own installation directory if a file .path.cfg exists.
If the file exists, then use the user customized workdir from inside. Otherwise use default workingdir
