### ISSUE TITLE
Broke system - Debian 12 - Installed through Discover - KDE

### ISSUE THREAD

**Issue by lilacdev** [szczyglis-dev/py-gpt#82]
Hi,

Just to let you know trying to install your application broke my system.

First it froze the system, then I lost all data in my Docker containers. After investigation, I found that you install Docker through Snap.

Not to mention that Snap can be painful for some of us, you should not install packages (especially packages like Docker) without checking if an existing one is already up and running...

I managed to uninstall all snap (Docker + PyGPT) and then a full reboot brought back all my stuff. Perhaps it will help anyone encountering this error.

**Comment by szczyglis-dev** [comment]
Yes, you are absolutely right, sorry for the confusion.

Since version `2.4.35` Docker has been removed from the dependencies in snapcraft.yml.

Regards.
